name: trigger_update

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  check_date:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check_date.outputs.should_run }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Latest Commit
        id: check_date
        run: |
          if test -z $(git rev-list --after="24 hours" ${{ github.sha }}); then
            echo "should_run=false" >> $GITHUB_ENV
            echo "::set-output name=should_run::false"
            echo "Latest commit is older than 24 hours."
          else
            echo "should_run=true" >> $GITHUB_ENV
            echo "::set-output name=should_run::true"
            echo "Latest commit is within the last 24 hours."
          fi
          
  trigger_update:
    needs: check_date
    runs-on: ubuntu-latest
    if: ${{ needs.check_date.outputs.should_run == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Trigger Update
        run: |
          echo "Triggering update because should_run is true."
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/poiroe/poiroe.github.io/dispatches \
            -d '{"event_type": "trigger-update"}')
          echo "Response: $response"
