name: Trigger Update on picx-images-hosting

on:
  push:
    branches:
      - master

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Check Delay File
        run: |
          delay_file="${GITHUB_WORKSPACE}/delay"
          if [ -f "$delay_file" ]; then
            last_modified=$(stat -c %Y "$delay_file")
            current_time=$(date +%s)
            time_diff=$((current_time - last_modified))
            
            if [ "$time_diff" -lt 60 ]; then
              echo "Delay time is less than 1 minute. Exiting GitHub Actions."
              exit 0
            else
              echo "Delay time is greater than or equal to 1 minute. Updating delay file and waiting for 1 minute."
              echo "update" > "$delay_file"
              sleep 60
            fi
          else
            echo "Delay file not found. Creating delay file."
            echo "update" > "$delay_file"
            sleep 60
          fi

      - name: Trigger Update
        run: |
          curl -XPOST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/picx-images-hosting/picx-images-hosting/dispatches \
            -d '{"event_type": "trigger-update"}'
