name: My Workflow1

on:
  schedule:
    - cron: '*/3 * * * *'  # Run daily

jobs:
  check_date:
    runs-on: ubuntu-latest
    steps:
      - id: should_run
        continue-on-error: true
        name: Check Latest Commit
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "Current SHA: ${{ github.sha }}"
          echo "Current time: $(date -u)"
          echo "Commits in the last 24 hours:"
          git log --since="24 hours" --pretty=oneline
          if test -z $(git rev-list --after="24 hours" ${{ github.sha }}); then
            echo "No commits in the last 24 hours. Setting should_run to false."
            echo "::set-output name=should_run::false"
          else
            echo "Commits found in the last 24 hours. should_run remains unchanged."
          fi

  trigger_update:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Trigger Update on poiroe.github.io
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8

      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Trigger Update
        run: |
          curl -XPOST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/poiroe/poiroe.github.io/dispatches \
            -d '{"event_type": "trigger-update"}'
