name: Trigger Update on poiroe.github.io

on:
  push:
    branches:
      - master

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Check Last Trigger Time
        run: |
          DELAY_FILE_PATH="delay"
          # Check if the delay file exists
          if [ -f "$DELAY_FILE_PATH" ]; then
            # Get the creation time of the delay file
            CREATION_TIME=$(stat -c %Y "$DELAY_FILE_PATH")
            # Get the current time
            CURRENT_TIME=$(date +%s)
            # Calculate the time difference
            TIME_DIFF=$((CURRENT_TIME - CREATION_TIME))
            
            # Check if the time difference is greater than 1 minute
            if [ "$TIME_DIFF" -lt 60 ]; then
              echo "Time interval is less than 1 minute. Skipping the workflow."
              exit 0
            fi
          fi

      - name: Update Delay File
        run: |
          DELAY_FILE_PATH="delay"
          # Update the content of the delay file with the current time
          date +'%Y-%m-%dT%H:%M:%SZ' > "$DELAY_FILE_PATH"
        # Record a message indicating that the delay file has been updated
        echo "Delay file has been updated."

      - name: Trigger Update
        run: |
          sleep 60
          curl -XPOST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/poiroe/poiroe.github.io/dispatches \
            -d '{"event_type": "trigger-update"}'
        # Record a message indicating that the update has been sent
        echo "Trigger update has been sent."
